name: CI JS Calculator

on: 
  push: 
    branches: 
      - '**' 
  pull_request: 
    branches: 
      - '**' 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout of repository
        uses: actions/checkout@v4


      - name: Settings Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Build of proyect
        run: echo "Build is completed"
